kubectl replace -f /Users/john/Workspace/fundations/k8s/biz/app-upgrade-service/deployment.yaml
kubectl replace -f /Users/john/Workspace/fundations/k8s/biz/cloud-pharmacy-node-gateway/deployment.yaml
kubectl replace -f /Users/john/Workspace/fundations/k8s/biz/data-bridge/deployment-cron.yaml

kubectl replace -f /Users/john/Workspace/fundations/k8s/biz/data-bridge/deployment.yaml
kubectl replace -f /Users/john/Workspace/fundations/k8s/biz/data-viewer/deployment.yaml
kubectl replace -f /Users/john/Workspace/fundations/k8s/biz/e-mall/deployment.yaml
kubectl replace -f /Users/john/Workspace/fundations/k8s/biz/emall-cron/deployment.yaml
kubectl replace -f /Users/john/Workspace/fundations/k8s/biz/fzapi/deployment.yaml
kubectl replace -f /Users/john/Workspace/fundations/k8s/biz/grape-http/deployment-crontab.yaml
kubectl replace -f /Users/john/Workspace/fundations/k8s/biz/grape-http/deployment.yaml

kubectl replace -f /Users/john/Workspace/fundations/k8s/biz/hospital-cooperation/med-hc-manage/deployment.crontab.yaml
kubectl replace -f /Users/john/Workspace/fundations/k8s/biz/hospital-cooperation/med-hc-manage/deployment.daemon.yaml
kubectl replace -f /Users/john/Workspace/fundations/k8s/biz/hospital-cooperation/med-hc-manage/deployment.yaml
kubectl replace -f /Users/john/Workspace/fundations/k8s/biz/hospital-cooperation/med-hc-medication/deployment.yaml
kubectl replace -f /Users/john/Workspace/fundations/k8s/biz/hospital-cooperation/med-hc-service/deployment.crontab.yaml
kubectl replace -f /Users/john/Workspace/fundations/k8s/biz/hospital-cooperation/med-hc-service/deployment.daemon.yaml
kubectl replace -f /Users/john/Workspace/fundations/k8s/biz/hospital-cooperation/med-hc-service/deployment.yaml
kubectl replace -f /Users/john/Workspace/fundations/k8s/biz/hospital-cooperation/med-hc-user/deployment.yaml
kubectl replace -f /Users/john/Workspace/fundations/k8s/biz/internal-openapi/deployment.yaml
kubectl replace -f /Users/john/Workspace/fundations/k8s/biz/manage-android/deployment.yaml
kubectl replace -f /Users/john/Workspace/fundations/k8s/biz/mecrm/deployment.crontab.yaml
kubectl replace -f /Users/john/Workspace/fundations/k8s/biz/mecrm/deployment.yaml
kubectl replace -f /Users/john/Workspace/fundations/k8s/biz/med-activity-budget/deployment.yaml
kubectl replace -f /Users/john/Workspace/fundations/k8s/biz/med-app-task/deployment.yaml
kubectl replace -f /Users/john/Workspace/fundations/k8s/biz/med-auth/deployment.yaml
kubectl replace -f /Users/john/Workspace/fundations/k8s/biz/med-broker-app/deployment.yaml
kubectl replace -f /Users/john/Workspace/fundations/k8s/biz/med-broker-wallet/deployment.yaml

kubectl replace -f /Users/john/Workspace/fundations/k8s/biz/med-broker/deployment-grpc.yaml
kubectl replace -f /Users/john/Workspace/fundations/k8s/biz/med-cdm-schedule/deployment.yaml
kubectl replace -f /Users/john/Workspace/fundations/k8s/biz/med-cdm/deployment.yaml
kubectl replace -f /Users/john/Workspace/fundations/k8s/biz/med-cloud-pharmacy-grpc/deployment-grpc.yaml
kubectl replace -f /Users/john/Workspace/fundations/k8s/biz/med-cloud-pharmacy/deployment.yaml
kubectl replace -f /Users/john/Workspace/fundations/k8s/biz/med-cloud-wallet/deployment.yaml
kubectl replace -f /Users/john/Workspace/fundations/k8s/biz/med-cooperate-data/deployment.yaml
kubectl replace -f /Users/john/Workspace/fundations/k8s/biz/med-cooperate-medication/deployment.yaml
kubectl replace -f /Users/john/Workspace/fundations/k8s/biz/med-d2d-ph/deployment.crontab.yaml
kubectl replace -f /Users/john/Workspace/fundations/k8s/biz/med-d2d-ph/deployment.daemon.yaml
kubectl replace -f /Users/john/Workspace/fundations/k8s/biz/med-d2d-ph/deployment.yaml
kubectl replace -f /Users/john/Workspace/fundations/k8s/biz/med-d2d/deployment.crontab.yaml
kubectl replace -f /Users/john/Workspace/fundations/k8s/biz/med-d2d/deployment.daemon-second.yaml
kubectl replace -f /Users/john/Workspace/fundations/k8s/biz/med-d2d/deployment.daemon.yaml
kubectl replace -f /Users/john/Workspace/fundations/k8s/biz/med-d2d/deployment.yaml

kubectl replace -f /Users/john/Workspace/fundations/k8s/biz/med-data-tag/deployment.yaml
kubectl replace -f /Users/john/Workspace/fundations/k8s/biz/med-data/deployment.yaml
kubectl replace -f /Users/john/Workspace/fundations/k8s/biz/med-doctor-aid/deployment.yaml
kubectl replace -f /Users/john/Workspace/fundations/k8s/biz/med-doctor-app/deployment.yaml
kubectl replace -f /Users/john/Workspace/fundations/k8s/biz/med-doctor-grpc/deployment.yaml
kubectl replace -f /Users/john/Workspace/fundations/k8s/biz/med-egg-m/deployment.yaml
kubectl replace -f /Users/john/Workspace/fundations/k8s/biz/med-fit/deployment.yaml

kubectl replace -f /Users/john/Workspace/fundations/k8s/biz/med-hc-manage-hz/deployment.yaml
kubectl replace -f /Users/john/Workspace/fundations/k8s/biz/med-hc-manage-sc/deployment.crontab.yaml
kubectl replace -f /Users/john/Workspace/fundations/k8s/biz/med-hc-manage-sc/deployment.yaml
kubectl replace -f /Users/john/Workspace/fundations/k8s/biz/med-hc-manage-xj/deployment.yaml
kubectl replace -f /Users/john/Workspace/fundations/k8s/biz/med-hc-manage/deployment.crontab.yaml
kubectl replace -f /Users/john/Workspace/fundations/k8s/biz/med-hc-manage/deployment.yaml
kubectl replace -f /Users/john/Workspace/fundations/k8s/biz/med-hc-medication/deployment.yaml
kubectl replace -f /Users/john/Workspace/fundations/k8s/biz/med-hc-service-hz/deployment.crontab.yaml
kubectl replace -f /Users/john/Workspace/fundations/k8s/biz/med-hc-service-hz/deployment.daemon.yaml
kubectl replace -f /Users/john/Workspace/fundations/k8s/biz/med-hc-service-hz/deployment.yaml
kubectl replace -f /Users/john/Workspace/fundations/k8s/biz/med-hc-service-sc/deployment.crontab.yaml
kubectl replace -f /Users/john/Workspace/fundations/k8s/biz/med-hc-service-sc/deployment.daemon.yaml
kubectl replace -f /Users/john/Workspace/fundations/k8s/biz/med-hc-service-sc/deployment.yaml
kubectl replace -f /Users/john/Workspace/fundations/k8s/biz/med-hc-service-xj/deployment.crontab.yaml
kubectl replace -f /Users/john/Workspace/fundations/k8s/biz/med-hc-service-xj/deployment.daemon.yaml
kubectl replace -f /Users/john/Workspace/fundations/k8s/biz/med-hc-service-xj/deployment.yaml
kubectl replace -f /Users/john/Workspace/fundations/k8s/biz/med-hc-service/deployment.crontab.yaml
kubectl replace -f /Users/john/Workspace/fundations/k8s/biz/med-hc-service/deployment.daemon.yaml
kubectl replace -f /Users/john/Workspace/fundations/k8s/biz/med-hc-service/deployment.yaml
kubectl replace -f /Users/john/Workspace/fundations/k8s/biz/med-hc-user-hz/deployment.yaml
kubectl replace -f /Users/john/Workspace/fundations/k8s/biz/med-hc-user-sc/deployment.yaml
kubectl replace -f /Users/john/Workspace/fundations/k8s/biz/med-hc-user-xj/deployment.yaml
kubectl replace -f /Users/john/Workspace/fundations/k8s/biz/med-hc-user/deployment.yaml

kubectl replace -f /Users/john/Workspace/fundations/k8s/biz/med-ih-activity/deployment.yaml
kubectl replace -f /Users/john/Workspace/fundations/k8s/biz/med-ih-broker/deployment.yaml
kubectl replace -f /Users/john/Workspace/fundations/k8s/biz/med-ih-community/deployment.yaml
kubectl replace -f /Users/john/Workspace/fundations/k8s/biz/med-ih-listener/deployment.yaml
kubectl replace -f /Users/john/Workspace/fundations/k8s/biz/med-ih-medication/deployment-cron.yaml
kubectl replace -f /Users/john/Workspace/fundations/k8s/biz/med-ih-medication/deployment.yaml
kubectl replace -f /Users/john/Workspace/fundations/k8s/biz/med-ih-online/deployment.yaml
kubectl replace -f /Users/john/Workspace/fundations/k8s/biz/med-ih-openapi/deployment.yaml
kubectl replace -f /Users/john/Workspace/fundations/k8s/biz/med-ih-order/deployment.yaml
kubectl replace -f /Users/john/Workspace/fundations/k8s/biz/med-ih-panel/deployment.yaml
kubectl replace -f /Users/john/Workspace/fundations/k8s/biz/med-ih-pres/deployment.yaml
kubectl replace -f /Users/john/Workspace/fundations/k8s/biz/med-ih-service/deployment.yaml
kubectl replace -f /Users/john/Workspace/fundations/k8s/biz/med-ih-ticket/deployment.yaml
kubectl replace -f /Users/john/Workspace/fundations/k8s/biz/med-im-web/deployment.yaml
kubectl replace -f /Users/john/Workspace/fundations/k8s/biz/med-im/backend/deployment-ass.yaml
kubectl replace -f /Users/john/Workspace/fundations/k8s/biz/med-im/backend/deployment-inq.yaml
kubectl replace -f /Users/john/Workspace/fundations/k8s/biz/med-im/backend/deployment-inquiry.yaml
kubectl replace -f /Users/john/Workspace/fundations/k8s/biz/med-im/backend/deployment.yaml
kubectl replace -f /Users/john/Workspace/fundations/k8s/biz/med-im/server/deployment.yaml

kubectl replace -f /Users/john/Workspace/fundations/k8s/biz/med-inquiry/backend/deployment.yaml
kubectl replace -f /Users/john/Workspace/fundations/k8s/biz/med-inquiry/cron/deployment.yaml
kubectl replace -f /Users/john/Workspace/fundations/k8s/biz/med-inquiry/kafka/deployment-kafka.yaml
kubectl replace -f /Users/john/Workspace/fundations/k8s/biz/med-inquiry/openapi/deployment.yaml
kubectl replace -f /Users/john/Workspace/fundations/k8s/biz/med-inquiry/panel/deployment.yaml
kubectl replace -f /Users/john/Workspace/fundations/k8s/biz/med-inquiry/web/deployment.yaml
kubectl replace -f /Users/john/Workspace/fundations/k8s/biz/med-medication/deployment.yaml
kubectl replace -f /Users/john/Workspace/fundations/k8s/biz/med-msg-svr/deployment-master.yaml
kubectl replace -f /Users/john/Workspace/fundations/k8s/biz/med-msg-svr/deployment-worker.yaml
kubectl replace -f /Users/john/Workspace/fundations/k8s/biz/med-node-tool/deployment.yaml
kubectl replace -f /Users/john/Workspace/fundations/k8s/biz/med-oop/deployment.crontab.yaml
kubectl replace -f /Users/john/Workspace/fundations/k8s/biz/med-oop/deployment.yaml
kubectl replace -f /Users/john/Workspace/fundations/k8s/biz/med-open-web/deployment.yaml
kubectl replace -f /Users/john/Workspace/fundations/k8s/biz/med-openapi-go/deployment.yaml
kubectl replace -f /Users/john/Workspace/fundations/k8s/biz/med-order/deployment-grpc.yaml
kubectl replace -f /Users/john/Workspace/fundations/k8s/biz/med-order/deployment-web.yaml
kubectl replace -f /Users/john/Workspace/fundations/k8s/biz/med-panel/deployment.yaml
kubectl replace -f /Users/john/Workspace/fundations/k8s/biz/med-patient-archives/deployment.yaml
kubectl replace -f /Users/john/Workspace/fundations/k8s/biz/med-patient-medication/deployment.yaml
kubectl replace -f /Users/john/Workspace/fundations/k8s/biz/med-patient/deployment-grpc.yaml
kubectl replace -f /Users/john/Workspace/fundations/k8s/biz/med-pay/deployment.crontab.yaml
kubectl replace -f /Users/john/Workspace/fundations/k8s/biz/med-pay/deployment.daemon.yaml
kubectl replace -f /Users/john/Workspace/fundations/k8s/biz/med-pay/deployment.yaml

kubectl replace -f /Users/john/Workspace/fundations/k8s/biz/med-payment-cron/deployment.yaml
kubectl replace -f /Users/john/Workspace/fundations/k8s/biz/med-payment/deployment.yaml
kubectl replace -f /Users/john/Workspace/fundations/k8s/biz/med-prescription/deployment.yaml
kubectl replace -f /Users/john/Workspace/fundations/k8s/biz/med-push/deployment.yaml
kubectl replace -f /Users/john/Workspace/fundations/k8s/biz/med-questionnaire/deployment.crontab.yaml
kubectl replace -f /Users/john/Workspace/fundations/k8s/biz/med-questionnaire/deployment.yaml
kubectl replace -f /Users/john/Workspace/fundations/k8s/biz/med-quiz-mini/deployment.yaml
kubectl replace -f /Users/john/Workspace/fundations/k8s/biz/med-quiz/statefulset.yaml
kubectl replace -f /Users/john/Workspace/fundations/k8s/biz/med-react-ssr/deployment.yaml
kubectl replace -f /Users/john/Workspace/fundations/k8s/biz/med-recomend/deployment.yaml
kubectl replace -f /Users/john/Workspace/fundations/k8s/biz/med-sample-oop/deployment.yaml
kubectl replace -f /Users/john/Workspace/fundations/k8s/biz/med-search/deployment.daemon.yaml
kubectl replace -f /Users/john/Workspace/fundations/k8s/biz/med-search/deployment.yaml
kubectl replace -f /Users/john/Workspace/fundations/k8s/biz/med-service/backend/deployment.yaml
kubectl replace -f /Users/john/Workspace/fundations/k8s/biz/med-service/cron/deployment.yaml
kubectl replace -f /Users/john/Workspace/fundations/k8s/biz/med-ticket/deployment.yaml
kubectl replace -f /Users/john/Workspace/fundations/k8s/biz/med-user-grpc/grpc/backend/deployment.yaml
kubectl replace -f /Users/john/Workspace/fundations/k8s/biz/med-user-grpc/grpc/deployment.yaml
kubectl replace -f /Users/john/Workspace/fundations/k8s/biz/med-user/deployment.yaml

kubectl replace -f /Users/john/Workspace/fundations/k8s/biz/med-wechat/deployment-web.yaml
kubectl replace -f /Users/john/Workspace/fundations/k8s/biz/med3-app-h5/deployment.yaml
kubectl replace -f /Users/john/Workspace/fundations/k8s/biz/med3-app-panel/deployment.yaml
kubectl replace -f /Users/john/Workspace/fundations/k8s/biz/med3-app-web/deployment.daemon.yaml
kubectl replace -f /Users/john/Workspace/fundations/k8s/biz/med3-app-web/deployment.yaml
kubectl replace -f /Users/john/Workspace/fundations/k8s/biz/med3-app/deployment.yaml
kubectl replace -f /Users/john/Workspace/fundations/k8s/biz/med3-passport/deployment.yaml
kubectl replace -f /Users/john/Workspace/fundations/k8s/biz/med3-statistics/deployment.yaml
kubectl replace -f /Users/john/Workspace/fundations/k8s/biz/med3-svr-excel/deployment.yaml
kubectl replace -f /Users/john/Workspace/fundations/k8s/biz/med3-svr/deployment.crontab.yaml
kubectl replace -f /Users/john/Workspace/fundations/k8s/biz/med3-svr/deployment.daemon.yaml
kubectl replace -f /Users/john/Workspace/fundations/k8s/biz/med3-svr/deployment.yaml
kubectl replace -f /Users/john/Workspace/fundations/k8s/biz/med3-work-group/deployment.yaml
kubectl replace -f /Users/john/Workspace/fundations/k8s/biz/network-medical-faculty/network-medical-faculty.yaml
kubectl replace -f /Users/john/Workspace/fundations/k8s/biz/panel-node-gateway/deployment.yaml
kubectl replace -f /Users/john/Workspace/fundations/k8s/biz/proto-manage/deployment.yaml
kubectl replace -f /Users/john/Workspace/fundations/k8s/biz/recommen_label/deployment.yaml
kubectl replace -f /Users/john/Workspace/fundations/k8s/biz/report-helper/deployment.yaml
kubectl replace -f /Users/john/Workspace/fundations/k8s/biz/workstation-server/deployment.yaml

kubectl replace -f /Users/john/Workspace/fundations/k8s/infra/med-data-track/deployment.yaml
kubectl replace -f /Users/john/Workspace/fundations/k8s/infra/med-email/grpc/deployment.yaml
kubectl replace -f /Users/john/Workspace/fundations/k8s/infra/med-email/worker/deployment.yaml
kubectl replace -f /Users/john/Workspace/fundations/k8s/infra/med-files/deployment.yaml
kubectl replace -f /Users/john/Workspace/fundations/k8s/infra/med-monitor/grpc/deployment.yaml
kubectl replace -f /Users/john/Workspace/fundations/k8s/infra/med-monitor/pull/deployment.yaml
kubectl replace -f /Users/john/Workspace/fundations/k8s/infra/med-monitor/transfer/deployment.yaml
kubectl replace -f /Users/john/Workspace/fundations/k8s/infra/med-monitor/web/deployment.yaml
kubectl replace -f /Users/john/Workspace/fundations/k8s/infra/med-sms/grpc/deployment.yaml
kubectl replace -f /Users/john/Workspace/fundations/k8s/infra/med-sms/http/deployment.yaml
kubectl replace -f /Users/john/Workspace/fundations/k8s/infra/med-sms/worker/deployment.yaml
kubectl replace -f /Users/john/Workspace/fundations/k8s/infra/med-tim/deployment.yaml
kubectl replace -f /Users/john/Workspace/fundations/k8s/infra/nginx-ingress/daemonset.yaml
